CREATE DATABASE HR11;

USE HR11;

SELECT * FROM HR_1;

SELECT * FROM HR_2;

ALTER TABLE HR_2 RENAME COLUMN `EMPLOYEE ID`  TO EMPLOYEE_ID ;

-- JOINING TWO TABLE THROUGH COMMON COLUMN (EMPLOYEE ID)
CREATE TABLE HRDATA
SELECT * FROM HR_1 AS H1
JOIN HR_2 AS H2
ON (H1.EMPLOYEENUMBER = H2.EMPLOYEE_ID);

SELECT * FROM HRDATA;
ALTER TABLE HRDATA MODIFY COLUMN EMPLOYEE_ID INT FIRST;

-- DATE OF JOINING
ALTER TABLE HRDATA ADD COLUMN DATE_OF_JOINING DATE AFTER DAILYRATE;

UPDATE HRDATA
SET DATE_OF_JOINING = CONCAT(`Year of Joining`,'-',`Month of Joining`,'-',`Day of Joining`);
-- YEAR
SELECT DATE_OF_JOINING,YEAR(DATE_OF_JOINING) AS YEAR FROM HRDATA;
-- MONTH
SELECT DATE_OF_JOINING,MONTH(DATE_OF_JOINING) AS MONTH FROM HRDATA;
-- DAY
SELECT DATE_OF_JOINING,DAY(DATE_OF_JOINING) AS DAY FROM HRDATA;
-- MONTH FULL NAME
ALTER TABLE HRDATA ADD COLUMN MONTH_NAME VARCHAR(30) AFTER DATE_OF_JOINING;
UPDATE HRDATA 
SET MONTH_NAME = MONTHNAME(DATE_OF_JOINING);

SELECT * FROM HRDATA;
-- QUARTER 
ALTER TABLE HRDATA ADD COLUMN QUARTER_Q VARCHAR(10) AFTER MONTH_NAME;
UPDATE HRDATA SET QUARTER_Q = QUARTER(DATE_OF_JOINING);

-- YEAR MONTH
ALTER TABLE HRDATA ADD COLUMN YEARMONTH VARCHAR(20) AFTER MONTH_NAME;
UPDATE HRDATA
SET YEARMONTH = DATE_FORMAT(DATE_OF_JOINING,'%Y %M') ;

-- WEEKDAY NAME /DAY NAME
ALTER TABLE HRDATA ADD COLUMN DAY_NAME VARCHAR(30) AFTER DATE_OF_JOINING;
UPDATE HRDATA 
SET DAY_NAME = DAYNAME(DATE_OF_JOINING);

-- FINANICAL MONTH YEAR
ALTER TABLE HRDATA ADD COLUMN FINANCIAL_MONTH VARCHAR(30) AFTER DATE_OF_JOINING;

UPDATE HRDATA SET FINANCIAL_MONTH =
    CASE
        WHEN MONTH(DATE_OF_JOINING) >= 4 THEN CONCAT(YEAR(DATE_OF_JOINING), '-', LPAD(MONTH(DATE_OF_JOINING) - 3, 2, '0'))
        ELSE CONCAT(YEAR(DATE_OF_JOINING) - 1, '-', LPAD(MONTH(DATE_OF_JOINING) + 9, 2, '0'))
    END ;

-- FINANICAL QUARTER
ALTER TABLE HRDATA ADD COLUMN FINANCIAL_QUARTER VARCHAR(20) AFTER FINANCIAL_MONTH;
UPDATE HRDATA 
SET FINANCIAL_QUARTER =
    CASE
        WHEN MONTH(DATE_OF_JOINING) BETWEEN 4 AND 6 THEN CONCAT(YEAR(DATE_OF_JOINING), '-Q1')
        WHEN MONTH(DATE_OF_JOINING) BETWEEN 7 AND 9 THEN CONCAT(YEAR(DATE_OF_JOINING), '-Q2')
        WHEN MONTH(DATE_OF_JOINING) BETWEEN 10 AND 12 THEN CONCAT(YEAR(DATE_OF_JOINING), '-Q3')
        ELSE CONCAT(YEAR(DATE_OF_JOINING) - 1, '-Q4')
    END ;
    SELECT * FROM HRDATA;
    
   -- ATTRITION RATE
   ALTER TABLE HRDATA ADD COLUMN ATTRITION_RATE INT AFTER ATTRITION;
UPDATE HRDATA 
SET ATTRITION_RATE =  CASE ATTRITION WHEN 'YES' THEN 1
                   WHEN 'NO' THEN 0
	END;
    
SELECT * FROM HRDATA;

-- KPIs
-- 1. AVERAGE ATTRITION RATE FOR ALL DEPARTMENTS
CREATE VIEW KPI_1 AS SELECT DEPARTMENT,ROUND(AVG(ATTRITION_RATE)*100,2) AS AVERAGE FROM HRDATA
GROUP BY DEPARTMENT;

SELECT * FROM KPI_1;

-- 2. AVERAGE HOURLY RATE OF MALE RESERACH SCIENTIEST
CREATE VIEW KPI_2 AS SELECT JOBROLE, TRUNCATE(AVG(HOURLYRATE),2) AS `HOURLY RATE` FROM HRDATA
WHERE GENDER = 'MALE' AND JOBROLE = 'RESEARCH SCIENTIST'
GROUP BY JOBROLE;

SELECT * FROM KPI_2;

-- 3. ATTRITION RATE VS MONTHLY INCOME STATE
CREATE VIEW KPI_3 AS SELECT DEPARTMENT , ROUND(AVG(ATTRITION_RATE)*100,2) AS ATTRITION_AVG , ROUND(AVG(MONTHLYINCOME),2) AS MONTHLY_INCOME 
FROM HRDATA
GROUP BY DEPARTMENT;

SELECT * FROM KPI_3;

-- 4. AVERAGE WORKING YEAR FROM EACH DEPARTMENT
CREATE VIEW KPI_4 AS SELECT DEPARTMENT, TRUNCATE(AVG(TOTALWORKINGYEARS),2) AS `TOTAL WORKING YEARS` FROM HRDATA
GROUP BY DEPARTMENT;

SELECT * FROM KPI_4;

-- 5. DEPARTMENT WISE NO OF EMPLOYEES
CREATE VIEW KPI_5 AS SELECT DEPARTMENT, COUNT(EMPLOYEECOUNT) AS EMPLOYEE FROM HRDATA
GROUP BY DEPARTMENT;

SELECT * FROM KPI_5;

-- 6. COUNT OF EMPLOYEES BASED ON EDUCATIONAL FIELDS
CREATE VIEW KPI_6 AS SELECT EDUCATIONFIELD, COUNT(EMPLOYEENUMBER) AS EMPLOYEE FROM HRDATA
GROUP BY EDUCATIONFIELD;

SELECT * FROM KPI_6;

-- 7. JOB ROLE VS WORK LIFE BALANCE
CREATE VIEW KPI_7 AS SELECT JOBROLE , TRUNCATE(AVG(WORKLIFEBALANCE),2) AS `WORK LIFE BALACNE` FROM HRDATA
GROUP BY JOBROLE;

SELECT * FROM KPI_7;

-- 8. ATTRITION RATE VS YEAR SINCE LAST PROMOTION RELATION
CREATE VIEW KPI_8 AS SELECT DEPARTMENT, ROUND(AVG(ATTRITION_RATE)*100,2) AS ATTRITION_RATE, ROUND(AVG(YEARSSINCELASTPROMOTION)) AS 
`YEAR SINCE LAST PROMOTION` FROM HRDATA
GROUP BY DEPARTMENT;

SELECT * FROM KPI_8;

-- 9. GENDER BASED PERCENTAGE OF EMPLOYEE
CREATE VIEW KPI_9 AS SELECT GENDER, COUNT(EMPLOYEENUMBER) AS EMPLOYEE, 
        (COUNT(EMPLOYEENUMBER) / (SELECT COUNT(EMPLOYEENUMBER) FROM HRDATA)) *100 AS PERCENTAGE
        FROM HRDATA
GROUP BY GENDER;

SELECT * FROM KPI_9;

-- 10. MONTHLY NEW HIRE VS ATTRTION TRENDLINE
CREATE VIEW KPI_10 AS SELECT  MONTH_NAME,COUNT(EMPLOYEE_ID) AS MONTHLY_NEW_HIRE, ROUND(AVG(ATTRITION_RATE)*100,2) AS ATTRITION_RATE
FROM HRDATA
GROUP BY MONTH_NAME;

SELECT * FROM KPI_10;

-- 11. DEPARTMENT WISE JOB SATISFACTION
CREATE VIEW KPI_11 AS SELECT DEPARTMENT, TRUNCATE(AVG(JOBSATISFACTION),2) AS `JOB SATISFACTION` FROM HRDATA
GROUP BY DEPARTMENT;

SELECT * FROM KPI_11;

-- JOBROLE WISE JOB SATISAFACTION
CREATE VIEW KPI_12 AS SELECT JOBROLE, TRUNCATE(AVG(JOBSATISFACTION),2) AS `JOB SATISFACTION` FROM HRDATA
GROUP BY JOBROLE;

SELECT * FROM KPI_12;
USE HR11;
CREATE VIEW EMP AS SELECT COUNT(EMPLOYEE_ID) FROM HRDATA;
CREATE VIEW ACTEMP AS SELECT (COUNT(EMPLOYEE_ID) - SUM(ATTRITION_RATE)) AS ACTIVE_EMPLOYEE FROM HRDATA;

-- BUSINESS TRAVEL WITH PROMOTION RATE
CREATE VIEW KPI_13 AS SELECT BUSINESSTRAVEL, ROUND(AVG(YEARSSINCELASTPROMOTION)*10,2) AS PROMOTION_RATE FROM HRDATA
GROUP BY BUSINESSTRAVEL;
SELECT * FROM KPI_13;

-- STOCK OPTION LEVEL IMPACT ON RETENTION
CREATE VIEW KPI_14 AS SELECT STOCKOPTIONLEVEL, ROUND(AVG(ATTRITION_RATE)*100,2) AS RETENTION_RATE FROM HRDATA
GROUP BY STOCKOPTIONLEVEL;
SELECT * FROM KPI_14;

USE HR11;
SELECT * FROM HRDATA;
-- KPI
SELECT * FROM EMP ;    -- TOTAL EMPLOYEE
SELECT * FROM ACTEMP;  -- ACTIVE EMPLOYEE
SELECT * FROM KPI_1;   -- AVERAGE ATTRITION RATE FOR ALL DEPARTMENTS
SELECT * FROM KPI_2;   -- AVERAGE HOURLY RATE OF MALE RESERACH SCIENTIEST
SELECT * FROM KPI_3;   -- ATTRITION RATE VS MONTHLY INCOME STATE
SELECT * FROM KPI_4;   -- AVERAGE WORKING YEAR FROM EACH DEPARTMENT
SELECT * FROM KPI_5;   -- DEPARTMENT WISE NO OF EMPLOYEES
SELECT * FROM KPI_6;   -- COUNT OF EMPLOYEES BASED ON EDUCATIONAL FIELDS
SELECT * FROM KPI_7;   -- JOB ROLE VS WORK LIFE BALANCE
SELECT * FROM KPI_8;   -- ATTRITION RATE VS YEAR SINCE LAST PROMOTION RELATION
SELECT * FROM KPI_9;   -- GENDER BASED PERCENTAGE OF EMPLOYEE
SELECT * FROM KPI_10;  -- MONTHLY NEW HIRE VS ATTRTION TRENDLINE
SELECT * FROM KPI_11;  -- DEPARTMENT WISE JOB SATISFACTION
SELECT * FROM KPI_12;  -- JOBROLE WISE JOB SATISAFACTION
SELECT * FROM KPI_13;  -- PROMOTION RATE BY BUSINESS TRAVEL
SELECT * FROM KPI_14;  -- STOCK OPTION LEVEL ON EMPLOYEE RETENTION